=== zhu-yiqi/agent-data-protocol/datasets/llava_plus/schema_raw.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "unique_id": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "conversations": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "from": {
            "type": "string",
            "enum": ["human", "gpt"]
          },
          "value": {
            "type": "string"
          },
          "thoughts": {
            "type": "string"
          },
          "actions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "API_name": {
                  "type": "string"
                },
                "API_params": {
                  "type": "object",
                  "properties": {
                    "boxes": {
                      "type": "array",
                      "items": {
                        "type": "array",
                        "items": {
                          "type": "number"
                        },
                        "minItems": 4,
                        "maxItems": 4
                      }
                    },
                    "prompt": {
                      "type": "string"
                    }
                  }
                }
              },
              "required": ["API_name", "API_params"]
            }
          }
        },
        "required": ["from", "value"]
      }
    },
    "data_source": {
      "type": "string"
    }
  },
  "required": ["unique_id", "image", "conversations", "data_source"]
  
}

=== zhu-yiqi/agent-data-protocol/datasets/llava_plus/sample_raw.json
[
  {
    "unique_id": "1699545382.4288898",
    "image": "000000436407.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nUsing the provided boxes as a visual guide, please segment the objects.\nThe input boxes are: [[0.0, 0.52, 0.1, 0.67]]"
      },
      {
        "from": "gpt",
        "thoughts": "SAM will assist in executing object segmentation for these input boxes.",
        "actions": [
          {
            "API_name": "sam",
            "API_params": {
              "boxes": [
                [
                  0.0,
                  0.52,
                  0.1,
                  0.67
                ]
              ]
            }
          }
        ],
        "value": "I will use sam to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "sam model outputs: {'message': 'The SAM has processed the image.'}\n\nsummarize the model outputs and answer my first answer: Using the provided boxes as a visual guide, please segment the objects.\nThe input boxes are: [[0.0, 0.52, 0.1, 0.67]]"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of sam. I can answer the question better.",
        "actions": [],
        "value": "Certainly! To segment the objects based on the provided boxes, we utilized SAM, which leverages bounding boxes for segmentation. Each object is segmented to generate a single output. The resulting segmented objects are now displayed below."
      },
      {
        "from": "human",
        "value": "How can I replace the segmented banana with broccoli in the masked region?"
      },
      {
        "from": "gpt",
        "thoughts": "To complete the task, I require the stable diffusion inpainting model.",
        "actions": [
          {
            "API_name": "inpainting",
            "API_params": {
              "prompt": "A pan of cooked potatoes and broccoli on a metal rack."
            }
          }
        ],
        "value": "I will use inpainting to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "inpainting model outputs: {'message': 'The stable diffusion inpainting has processed the image.'}\n\nsummarize the model outputs and answer my first answer: How can I replace the segmented banana with broccoli in the masked region?"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of inpainting. I can answer the question better.",
        "actions": [],
        "value": "Certainly! I completed the task of replacing the segmented banana with broccoli in the masked region. The outcomes have been displayed below."
      }
    ],
    "data_source": "coco"
  },
  {
    "unique_id": "1699545382.4288979",
    "image": "000000032626.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "Can you use the provided boxes as a guide to segment the items?\nThe input boxes are: [[0.3, 0.21, 0.33, 0.23]]\n<image>"
      },
      {
        "from": "gpt",
        "thoughts": "SAM (Segment Anything Model) is required to assist with ordering objects for the input boxes.",
        "actions": [
          {
            "API_name": "sam",
            "API_params": {
              "boxes": [
                [
                  0.3,
                  0.21,
                  0.33,
                  0.23
                ]
              ]
            }
          }
        ],
        "value": "I will use sam to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "sam model outputs: {'message': 'The SAM has processed the image.'}\n\nsummarize the model outputs and answer my first answer: Can you use the provided boxes as a guide to segment the items?\nThe input boxes are: [[0.3, 0.21, 0.33, 0.23]]"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of sam. I can answer the question better.",
        "actions": [],
        "value": "Sure, I can use the provided boxes to segment the items in the image using SAM, which can generate mask outputs using box hints to solve the task. Each prompt generates one output. Here are the results:"
      },
      {
        "from": "human",
        "value": "How can I modify the masked region to depict an airplane instead of the segmented person?"
      },
      {
        "from": "gpt",
        "thoughts": "To complete the task, I require the stable diffusion inpainting model.",
        "actions": [
          {
            "API_name": "inpainting",
            "API_params": {
              "prompt": "A man standing next to a cart filled with pizzas, with an airplane seamlessly replacing the segmented person."
            }
          }
        ],
        "value": "I will use inpainting to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "inpainting model outputs: {'message': 'The stable diffusion inpainting has processed the image.'}\n\nsummarize the model outputs and answer my first answer: How can I modify the masked region to depict an airplane instead of the segmented person?"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of inpainting. I can answer the question better.",
        "actions": [],
        "value": "Yes, I can assist you in modifying the masked region to portray an airplane instead of the segmented person. Here is the modified version of the image:"
      }
    ],
    "data_source": "coco"
  },
  {
    "unique_id": "1699545382.4289012",
    "image": "000000326511.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nCan you please use the provided boxes to segment the objects?\nThe input boxes are: [[0.25, 0.24, 0.57, 0.99]]"
      },
      {
        "from": "gpt",
        "thoughts": "SAM (Segment Anything Model) can be utilized to enable the segmentation of objects for input boxes, which can benefit me.",
        "actions": [
          {
            "API_name": "sam",
            "API_params": {
              "boxes": [
                [
                  0.25,
                  0.24,
                  0.57,
                  0.99
                ]
              ]
            }
          }
        ],
        "value": "I will use sam to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "sam model outputs: {'message': 'The SAM has processed the image.'}\n\nsummarize the model outputs and answer my first answer: Can you please use the provided boxes to segment the objects?\nThe input boxes are: [[0.25, 0.24, 0.57, 0.99]]"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of sam. I can answer the question better.",
        "actions": [],
        "value": "Yes, we can definitely address the problem by using SAM, an algorithm that performs segmentation based on bounding boxes. We have received one rectangle as input, and it will produce one mask. Here are some examples of the results of this process:"
      },
      {
        "from": "human",
        "value": "How can I replace the segmented region of a giraffe with a surfboard?"
      },
      {
        "from": "gpt",
        "thoughts": "In order to complete the task, I require the stable diffusion inpainting model.",
        "actions": [
          {
            "API_name": "inpainting",
            "API_params": {
              "prompt": "Two giraffes standing next to each other crossing necks and rubbing heads, with one giraffe holding a surfboard instead of its head."
            }
          }
        ],
        "value": "I will use inpainting to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "inpainting model outputs: {'message': 'The stable diffusion inpainting has processed the image.'}\n\nsummarize the model outputs and answer my first answer: How can I replace the segmented region of a giraffe with a surfboard?"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of inpainting. I can answer the question better.",
        "actions": [],
        "value": "Yes, I can assist you in replacing the segmented region of a giraffe with a surfboard. Here are the results of the task: [insert image result here]."
      }
    ],
    "data_source": "coco"
  },
  {
    "unique_id": "1699545382.4289033",
    "image": "000000064612.jpg",
    "conversations": [
      {
        "from": "human",
        "value": "<image>\nUsing the provided boxes as a reference, please segment the objects.\nThe input boxes are: [[0.54, 0.57, 0.63, 0.63]]"
      },
      {
        "from": "gpt",
        "thoughts": "The use of SAM (Segment Anything Model) is essential for identifying objects based on the provided input boxes.",
        "actions": [
          {
            "API_name": "sam",
            "API_params": {
              "boxes": [
                [
                  0.54,
                  0.57,
                  0.63,
                  0.63
                ]
              ]
            }
          }
        ],
        "value": "I will use sam to help to answer the question. Please wait for a moment."
      },
      {
        "from": "human",
        "value": "sam model outputs: {'message': 'The SAM has processed the image.'}\n\nsummarize the model outputs and answer my first answer: Using the provided boxes as a reference, please segment the objects.\nThe input boxes are: [[0.54, 0.57, 0.63, 0.63]]"
      },
      {
        "from": "gpt",
        "thoughts": "Thanks to the output of sam. I can answer the question better.",
        "actions": [],
