=== zhu-yiqi/agent-data-protocol/datasets/omniact/schema_raw.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "task": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "ocr": {
      "type": "object",
      "properties": {
        "text": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "value": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
          }
        }
      },
      "required": ["text", "value"]
    },
    "color": {
      "type": "object",
      "properties": {
        "text": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "value": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
          }
        }
      },
      "required": ["text", "value"]
    },
    "icon": {
      "type": "object",
      "properties": {
        "text": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "value": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
          }
        }
      },
      "required": ["text", "value"]
    },
    "box": {
      "type": "object",
      "properties": {
        "top_left": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
          }
        },
        "bottom_right": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
          }
        },
        "label": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["top_left", "bottom_right", "label"]
    }
  },
  "required": ["id", "task", "image", "ocr", "color", "icon", "box"]
  
}

=== zhu-yiqi/agent-data-protocol/datasets/omniact/sample_raw.json
[
  {
    "id": "train_0",
    "task": "Task: Review the products added to the cart\nOutput Script:\npyautogui.click(1288.5,116.0)",
    "image": "data/data/web/asics/screen1.png",
    "ocr": {
      "text": [
        "Home",
        "/",
        "Running",
        "Kids",
        " ",
        "Category",
        "Product",
        "Type",
        "Activity",
        "Width",
        "Color",
        "Price",
        "Pronation",
        "Goal",
        "Cushion",
        "Surface",
        "Model",
        "Join",
        "OneASICS\u2122",
        "and",
        "get",
        "exclusive",
        "perks,",
        "like",
        "free",
        "shipping",
        "on",
        "orders",
        "of",
        "$50+",
        "10%",
        "off*",
        "your",
        "first",
        "order.",
        "Sign",
        "Up",
        "Now",
        ">",
        "Make",
        "an",
        "online",
        "or",
        "in-store",
        "purchase",
        "now",
        "through",
        "12/21,",
        "a",
        "discount",
        "code",
        "12/22",
        "for",
        "$20",
        "any",
        "future",
        "$75",
        "more.",
        "*Terms",
        "apply.",
        "Shop",
        "+",
        "Kids'",
        "Shoes",
        "(259)",
        "29",
        "GRADE",
        "SCHOOL"
      ],
      "value": [
        [
          143.0,
          218.0
        ],
        [
          238.5,
          218.0
        ],
        [
          491.0,
          568.5
        ],
        [
          146.5,
          261.0
        ],
        [
          712.0,
          748.5
        ],
        [
          159.0,
          370.0
        ],
        [
          155.0,
          418.5
        ],
        [
          197.5,
          420.0
        ],
        [
          155.0,
          471.0
        ],
        [
          149.0,
          519.5
        ],
        [
          147.0,
          570.5
        ],
        [
          146.5,
          620.5
        ],
        [
          160.5,
          671.5
        ],
        [
          143.5,
          721.5
        ],
        [
          155.0,
          772.5
        ],
        [
          154.0,
          822.5
        ],
        [
          149.5,
          873.5
        ],
        [
          385.5,
          19.5
        ],
        [
          516.0,
          20.5
        ],
        [
          732.0,
          165.5
        ],
        [
          757.0,
          167.5
        ],
        [
          557.5,
          21.0
        ],
        [
          608.5,
          21.0
        ],
        [
          642.0,
          21.0
        ],
        [
          670.5,
          21.0
        ],
        [
          712.5,
          20.5
        ],
        [
          880.0,
          167.0
        ],
        [
          820.5,
          19.5
        ],
        [
          629.0,
          184.5
        ],
        [
          838.5,
          21.0
        ],
        [
          893.5,
          21.0
        ],
        [
          988.5,
          165.5
        ],
        [
          953.0,
          21.0
        ],
        [
          983.5,
          21.0
        ],
        [
          1020.0,
          21.0
        ],
        [
          1058.5,
          22.5
        ],
        [
          698.0,
          40.0
        ],
        [
          854.5,
          184.5
        ],
        [
          874.0,
          185.5
        ],
        [
          388.5,
          165.5
        ],
        [
          416.0,
          167.0
        ],
        [
          446.0,
          165.5
        ],
        [
          671.5,
          186.0
        ],
        [
          509.0,
          165.5
        ],
        [
          590.5,
          186.0
        ],
        [
          611.0,
          167.0
        ],
        [
          652.0,
          167.0
        ],
        [
          698.5,
          166.0
        ],
        [
          774.0,
          167.0
        ],
        [
          808.0,
          165.5
        ],
        [
          854.0,
          165.5
        ],
        [
          908.0,
          165.5
        ],
        [
          938.0,
          165.5
        ],
        [
          961.5,
          165.5
        ],
        [
          1015.0,
          168.5
        ],
        [
          1048.5,
          165.5
        ],
        [
          650.5,
          185.0
        ],
        [
          699.0,
          186.0
        ],
        [
          741.5,
          184.5
        ],
        [
          784.0,
          186.0
        ],
        [
          821.5,
          186.0
        ],
        [
          354.0,
          869.0
        ],
        [
          438.0,
          566.0
        ],
        [
          548.5,
          566.5
        ],
        [
          594.5,
          567.5
        ],
        [
          1150.0,
          891.5
        ],
        [
          1184.0,
          891.5
        ],
        [
          1237.0,
          891.5
        ]
      ]
    },
    "color": {
      "text": [],
      "value": []
    },
    "icon": {
      "text": [],
      "value": []
    },
    "box": {
      "top_left": [
        [
          1213.0,
          98.0
        ],
        [
          130.0,
          646.0
        ],
        [
          130.0,
          747.0
        ],
        [
          404.0,
          88.0
        ],
        [
          1017.0,
          100.0
        ],
        [
          130.0,
          545.0
        ],
        [
          130.0,
          696.0
        ],
        [
          130.0,
          444.0
        ],
        [
          130.0,
          393.0
        ],
        [
          243.0,
          211.0
        ],
        [
          130.0,
          292.0
        ],
        [
          461.0,
          88.0
        ],
        [
          269.0,
          88.0
        ],
        [
          1200.0,
          541.0
        ],
        [
          532.0,
          88.0
        ],
        [
          130.0,
          494.0
        ],
        [
          130.0,
          595.0
        ],
        [
          627.0,
          88.0
        ],
        [
          791.0,
          88.0
        ],
        [
          130.0,
          848.0
        ],
        [
          326.0,
          88.0
        ],
        [
          806.0,
          175.0
        ],
        [
          202.0,
          211.0
        ],
        [
          733.0,
          88.0
        ],
        [
          847.0,
          88.0
        ],
        [
          971.0,
          68.0
        ],
        [
          876.0,
          68.0
        ],
        [
          130.0,
          797.0
        ],
        [
          170.0,
          211.0
        ],
        [
          1232.0,
          68.0
        ],
        [
          130.0,
          86.0
        ],
        [
          1277.0,
          106.0
        ],
        [
          1072.0,
          68.0
        ],
        [
          1176.0,
          68.0
        ],
        [
          812.0,
          68.0
        ],
        [
          130.0,
          211.0
        ],
        [
          372.0,
          11.0
        ],
        [
          130.0,
          343.0
        ]
      ],
      "bottom_right": [
        [
          1242.0,
          132.0
        ],
        [
          360.0,
          695.0
        ],
        [
          360.0,
          796.0
        ],
        [
          461.0,
          144.0
        ],
        [
          1247.0,
          130.0
        ],
        [
          360.0,
          594.0
        ],
        [
          360.0,
          746.0
        ],
        [
          360.0,
          493.0
        ],
        [
          360.0,
          443.0
        ],
        [
          321.0,
          224.0
        ],
        [
          360.0,
          342.0
        ],
        [
          532.0,
          144.0
        ],
        [
          326.0,
          144.0
        ],
        [
          1299.0,
          579.0
        ],
        [
          627.0,
          144.0
        ],
        [
          360.0,
          544.0
        ],
        [
          360.0,
          645.0
        ],
        [
          733.0,
          144.0
        ],
        [
          847.0,
          144.0
        ],
        [
          360.0,
          897.0
        ],
        [
          404.0,
          144.0
        ],
        [
          878.0,
          193.0
        ],
        [
          241.0,
          224.0
        ],
        [
          791.0,
          144.0
        ],
        [
          907.0,
          144.0
        ],
        [
          1048.0,
          85.0
        ],
        [
          947.0,
          85.0
        ],
        [
          360.0,
          847.0
        ],
        [
          200.0,
          224.0
        ],
        [
          1310.0,
          85.0
        ],
        [
          241.0,
          146.0
        ],
        [
          1300.0,
          126.0
        ],
        [
          1152.0,
          85.0
        ],
        [
          1208.0,
          85.0
        ],
        [
          852.0,
          85.0
        ],
        [
          167.0,
          224.0
        ],
        [
          1068.0,
          46.0
        ],
        [
          360.0,
          392.0
        ]
      ],
      "label": [
        "search_button",
        "filter_by_pronation",
        "shows_cushioned_options",
        "view_kids_options",
        "search_bar",
        "select_by_Color",
        "filter_by_Goal",
        "redirect_to_product_filter_page",
        "filter_by_Product_Type",
        "load_running_shoes_options",
        "view_sizes",
        "Redirect_to_Sports",
        "redirect_to_mens_section",
        "filter_by_Newest",
        "redirect_to_sportstyle_options",
        "filter_by_width",
        "filter_by_price",
        "road_tested_options",
        "redirect_to_Sale",
        "expand_Model",
        "redirect_to_women",
